version: "3.8"
services:
  mongodb:
    image: mongo:6.0
    container_name: automated_job_finder_mongo_database
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: automated_job_finder_db
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
